### ISSUE TITLE
Subscribe checkbox

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/LyntonWeb#19] opened 2018-11-27 22:10 UTC
The checkbox is missing on some devices.

**URL tested:** http://blog.simsbuilders.com/blog

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPad Pro |
| Browser | Tablet_safari |
| Operating System | iOS 11.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/dc131431a3e0ed6e173cef369ce4901b4a0327a7/realios_iPad_Pro.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/dc131431a3e0ed6e173cef369ce4901b4a0327a7/realios_iPad_Pro.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPad+Pro&device_browser=safari&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fblog.simsbuilders.com%2Fblog&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=http://blog.simsbuilders.com/blog) to reproduce the issue on Browserstack:**

**Comment by NM-Computan** [comment] 2018-11-27 22:13
https://usersnap.com/a/#/your-team-wods/p/sims-f0ed74fc/81

The issue is marked as resolved in Usersnap.

**Comment by computan** [comment] 2018-11-28 09:14
Done

**Closed** 2018-11-29 15:47 UTC
